### ISSUE TITLE
Replace the content in `class3.md` with more relevant material

### ISSUE THREAD

**Issue by najsaqib** [PHACDataHub/git_github_intro#1]
@tomcdona If you get time and are interested, feel free to replace the content inside `class3.md` on command line interface with whatever you feel is better suited. I was thinking this could be a good place to talk about all the features on Github, such as project management, Github Actions, etc.

**Comment by tomcdona** [comment]
Just read through and I think you've covered enough in the one class. Basic understanding of how to create a branch and commit to it is likely enough for a new user.

I think a 4th class about issues, branching models, and pull/merge requests would be a good next step. I'd like to throw out a pull request with a 4th class attached and I'll add to it as I get the time, cool?

**Comment by tomcdona** [comment]
Hey Todd, go read classes 1 and 2 first before writing class 4! You're just re-inventing the wheel
